spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntaekeulgom@gmail.com
    password: 19288291
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4000
