spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: {your eamil}
    password: {email password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4000
